export const MODAL_TYPES = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  SIGN_IN_OPTIONS: "SIGN_IN_OPTIONS",
  SIGN_UP_OPTIONS: "SIGN_UP_OPTIONS",
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  CODE_VERIFICATION: "CODE_VERIFICATION",
};

export const QUERY_TYPES = {
  TAB: "TAB",
  TOPIC: "TOPIC",
};
