const ActionTypes = {
  AUTH: {
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
  },
  ARTICLE: {
    GET_ARTICLES: "GET_ARTICLES",
    GET_TRENDING_ARTICLES: "GET_TRENDING_ARTICLES",
    LOAD_MORE_ARTICLES: "LOAD_MORE_ARTICLES",
  },
  TOPICS: {
    GET_TRENDING_TOPICS: "GET_TRENDING_TOPICS",
  },
  MODALS: {
    SHOW_AUTH: "SHOW_AUTH",
    CLOSE_AUTH: "CLOSE_AUTH",
  }
};

export default ActionTypes;
